### ISSUE TITLE
Docker image with ARM support 

### ISSUE THREAD

**Issue by febarbosa182** [kube-green/kube-green#104]
Enable to run on Graviton 2 EC2 instances

**Comment by davidebianchi** [comment]
Hi @febarbosa182, yes I will add it in the next days

**Comment by davidebianchi** [comment]
I add the build with ARM platform to the pipeline. Can you check that the latest tag correctly works?

**Comment by davidebianchi** [comment]
Released in 0.3.1

**Comment by febarbosa182** [comment]
@davidebianchi Sorry for late update
It worked perfectly!

Thanks very much for this release!
