### ISSUE TITLE
Request: ARM64 support

### ISSUE THREAD

**Issue by AlexsJones** [kube-green/kube-green#166]
In order to run this on RaspberryPi clusters we would need arm64/armhf support.
Is this something you can add into the build chain?

**Comment by davidebianchi** [comment]
Hi @AlexsJones, sure!
For the RaspberryPi support, I suppose we should add the arm/v7 platform to the build chain.
I added it, can you try if the latest image works?
After that, I will release a new version.

**Comment by AlexsJones** [comment]
Thanks @davidebianchi for the quick response

I adjusted the controller-manager to `latest` but still see the same issue, should I adjust something else in the config?

<img width="629" alt="Screenshot 2022-07-24 at 18 00 30" src="https://user-images.githubusercontent.com/1235925/180658157-7c6b63ee-96da-4e3e-936b-55a90eda3ab2.png">

<img width="1208" alt="Screenshot 2022-07-24 at 18 00 35" src="https://user-images.githubusercontent.com/1235925/180658162-8f646d67-e526-4f58-aaa0-cff7e65a86a4.png">

**Comment by davidebianchi** [comment]
It's quite strange, I already use it with arm64 architecture. If you make a `docker inspect` of the downloaded image, what is the output?

**Comment by davidebianchi** [comment]
I close this issue as stale, please reopen if more support is needed.
