### ISSUE TITLE
Allow selecting excluded workloads with labels/annotations

### ISSUE THREAD

**Issue by aslafy-z** [kube-green/kube-green#172]
Provide a way for users to exclude deployments by adding a label (or annotation) to them instead of listing them in SleepInfo. This would be easier for clusters with a global policy (see #167), still letting users exclude their workloads from the scale down.

**Comment by davidebianchi** [comment]
Yes, it should be definitely an option to add in the roadmap

**Comment by davidebianchi** [comment]
This feature is released in [v0.5.0](https://github.com/kube-green/kube-green/releases/tag/v0.5.0)
