### ISSUE TITLE
Requirement of Cert-Manager

### ISSUE THREAD

**Issue by ctienshi** [kube-green/kube-green#201]
Documentation regarding the requirement of installing a cert-manager for Kube-green. Would be useful to understand the behaviour and the usage of Kube-green with a cert-manager.

**Comment by davidebianchi** [comment]
Hi @ctienshi, I would add it in the documentation.
Meanwhile, cert-manager is suggested to provide certificates for the webhook server. It is possible also to do it in other ways (so, without the use of cert-manager), but it's necessary to put the certificates in the desired location.
kube-green is based on kubebuilder scaffold, and [this](https://book.kubebuilder.io/cronjob-tutorial/cert-manager.html) is the base documentation. 
Do you need more in depth info?

**Comment by ctienshi** [comment]
Thanks @davidebianchi. I will checkout the documentation.

**Comment by teaton12** [comment]
Hi @davidebianchi, I realise this is an old issue but it’s relevant today, there is very little documentation on alternatives to cert-manager. I’ve gone through Kubebuilder scaffold but it’s not evident from here what’s required. 

I’ve issued a certificate in the namespace and associated it with the webhook but still hitting issues.

**Comment by davidebianchi** [comment]
I write a documentation on how to manually configure kube-green without the need of the cert-manager, now available on the [kube-green docs](https://kube-green.dev/docs/advanced/webhook-cert-management/).
I also added on the helm chart the possibility to enable an automatic cert configuration without the cert-manager (also documented in the above link).
