### ISSUE TITLE
Import `ko` tool to make development easier

### ISSUE THREAD

**Issue by jwcesign** [kube-green/kube-green#208]
Like this: https://github.com/knative/serving/blob/main/DEVELOPMENT.md

We only need to do like:
```sh
ko apply -Rf config/yaml/xxx
```
And don't need to build binary/builld image/load image and etc

Then everything is set up.

**Comment by davidebianchi** [comment]
Very interesting, I didn't known it. Thank you!
Can you open a PR to integrate it? Otherwise I will look into in the future.

**Comment by jwcesign** [comment]
sure
/assign
