### ISSUE TITLE
Does kube-green supported on k8s versions 1.24.9 or higher

### ISSUE THREAD

**Issue by saikumar0412** [kube-green/kube-green#261]
I would like to know whether kube-green is supported in k8s versions > 1.24 as I can see some errors while deploying `sleepInfo` controller in AKS version 1.24.9, where same `sleepInfo` yaml worked fine without any issues on 1.23.12.

sleepInfo.yaml:
```
apiVersion: kube-green.com/v1alpha1
kind: SleepInfo
metadata:
  name: working-hours
spec:
  weekdays: "*"
  timeZone: "Europe/Rome"
  sleepAt: "10:52"
  wakeUpAt: "10:54"
```

below is the error log from kube-green-controller.
```

2023-03-07T09:29:34Z    ERROR   controllers.SleepInfo   unable to fetch sleepInfo       {"sleepinfo": "default/working-hours", "error": "SleepInfo.kube-green.com \"working-hours\" not found"}
github.com/kube-green/kube-green/controllers/sleepinfo.(*SleepInfoReconciler).Reconcile
        /workspace/controllers/sleepinfo/sleepinfo_controller.go:80
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:122
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:323
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235
```

I found in the documentation that its currently supports (https://kube-green.dev/docs/install/#prerequisite) `>= 1.19 <=1.24` , however want to know when kube-green is available on k8s 1.24.9

**Comment by saikumar0412** [comment]
I guess its due to some syntactical error, its working on 1.24.6.

Please update documentation that >1.24 also supports

**Comment by saikumar0412** [comment]
@davidebianchi  I have a general question if a pod is not created as part of deployment I.e stand along pod, kube-green doesnt recognize that pod? I can see currently it supports only deployment and cronjob. Any ETA when it will be supporting for other resources like statefulsets etc.

**Comment by davidebianchi** [comment]
At the moment I have not an ETA, it's high priority in roadmap. Do you have some specific use case? Can you open a PR to support some resource? In issue #77 there are the next resources we want to support.

**Comment by saikumar0412** [comment]
Thanks @davidebianchi also one more suggestion is kube-rbac-proxy that you are using (v1.13.0) have 1 critical Vuln, consider using 1.14.0.

**Comment by davidebianchi** [comment]
Upgrade kube-rbac-proxy in https://github.com/kube-green/kube-green/releases/tag/v0.5.1
