### ISSUE TITLE
kube-green-controller-manager OOMKilled

### ISSUE THREAD

**Issue by sastorsl** [kube-green/kube-green#271]
### Issue
The `kube-green-controller-manager` is unable to start since the `manager` container is killed (due to the memory limit).
Issue has been present since `kube-green-0.5.0`

### Platform
* OpenShift 4.10.x
* `kube-green` installation through OpenShift community-operators

### Steps to reproduce

1. Install the `kube-green` operator (add "subscription" in OpenShift and install)
2. Pods are started
3. Container `kube-rbac-proxy` starts fine
4. Container `manager` fails to start after consuming memory above the limit

### Numbers

* 82 namespaces with `Sleepinfo`
* There should have been 86, based on the label.
* 145 pods in all 86 namespaces.

The number of namespaces / pods is ever increasing.

### Sleepinfo config via the OpenShift `NamespaceConfig`

```yaml
apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: sleepinfo
spec:
  labelSelector:
    matchLabels:
      custom.label.com/sleep-enabled: "true"
  templates:
  - excludedPaths:
    - .spec.rbac.policy
    - .spec.replicas
    - .metadata
    - .status
    objectTemplate: |
      apiVersion: kube-green.com/v1alpha1
      kind: SleepInfo
      metadata:
        name: default-sleep
        namespace: {{ .Name }}
        labels:
          app.kubernetes.io/managed-by: namespace-configuration-operator
      spec:
        weekdays: "*"
        sleepAt: "02:00"
        timeZone: "Europe/Oslo"
```

### Logs

```
openshift-operators)$ oc get pods -w
NAME                                                           READY   STATUS             RESTARTS        AGE
kube-green-controller-manager-88d764676-grtp7                  1/2     CrashLoopBackOff   6 (4m21s ago)   13m
kube-green-controller-manager-88d764676-grtp7                  1/2     Terminating        6 (4m29s ago)   13m
kube-green-controller-manager-88d764676-xc9hw                  0/2     Pending            0               0s
kube-green-controller-manager-88d764676-xc9hw                  0/2     Pending            0               0s
kube-green-controller-manager-88d764676-xc9hw                  0/2     ContainerCreating   0               1s
kube-green-controller-manager-88d764676-grtp7                  1/2     Terminating         6               13m
kube-green-controller-manager-88d764676-grtp7                  0/2     Terminating         6               13m
kube-green-controller-manager-88d764676-grtp7                  0/2     Terminating         6               13m
kube-green-controller-manager-88d764676-grtp7                  0/2     Terminating         6               13m
kube-green-controller-manager-88d764676-xc9hw                  0/2     ContainerCreating   0               2s
kube-green-controller-manager-88d764676-xc9hw                  1/2     Running             0               13s
kube-green-controller-manager-88d764676-xc9hw                  2/2     Running             0               21s
kube-green-controller-manager-88d764676-xc9hw                  1/2     OOMKilled           0               40s
kube-green-controller-manager-88d764676-xc9hw                  1/2     Running             1 (1s ago)      41s
kube-green-controller-manager-88d764676-xc9hw                  2/2     Running             1 (11s ago)     51s
kube-green-controller-manager-88d764676-xc9hw                  1/2     OOMKilled           1 (27s ago)     67s
kube-green-controller-manager-88d764676-xc9hw                  1/2     CrashLoopBackOff    1 (4s ago)      71s
kube-green-controller-manager-88d764676-xc9hw                  1/2     Running             2 (15s ago)     82s
kube-green-controller-manager-88d764676-xc9hw                  2/2     Running             2 (24s ago)     91s
kube-green-controller-manager-88d764676-xc9hw                  1/2     OOMKilled           2 (42s ago)     109s
kube-green-controller-manager-88d764676-xc9hw                  1/2     CrashLoopBackOff    2 (3s ago)      111s
kube-green-controller-manager-88d764676-xc9hw                  1/2     Running             3 (25s ago)     2m13s
kube-green-controller-manager-88d764676-xc9hw                  2/2     Running             3 (33s ago)     2m21s
kube-green-controller-manager-88d764676-xc9hw                  1/2     OOMKilled           3 (49s ago)     2m37s
kube-green-controller-manager-88d764676-xc9hw                  1/2     CrashLoopBackOff    3 (5s ago)      2m41s
kube-green-controller-manager-88d764676-xc9hw                  1/2     Running             4 (47s ago)     3m23s
kube-green-controller-manager-88d764676-xc9hw                  2/2     Running             4 (55s ago)     3m31s
kube-green-controller-manager-88d764676-xc9hw                  1/2     OOMKilled           4 (75s ago)     3m51s
kube-green-controller-manager-88d764676-xc9hw                  1/2     CrashLoopBackOff    4 (10s ago)     4m1s
kube-green-controller-manager-88d764676-xc9hw                  1/2     Running             5 (92s ago)     5m23s
kube-green-controller-manager-88d764676-xc9hw                  2/2     Running             5 (100s ago)    5m31s
kube-green-controller-manager-88d764676-xc9hw                  1/2     OOMKilled           5 (116s ago)    5m47s
kube-green-controller-manager-88d764676-xc9hw                  1/2     CrashLoopBackOff    5 (4s ago)      5m51s
kube-green-controller-manager-88d764676-xc9hw                  1/2     Running             6 (2m49s ago)   8m36s
kube-green-controller-manager-88d764676-xc9hw                  2/2     Running             6 (3m4s ago)    8m51s
kube-green-controller-manager-88d764676-xc9hw                  1/2     OOMKilled           6 (3m13s ago)   9m
kube-green-controller-manager-88d764676-xc9hw                  1/2     CrashLoopBackOff    6 (1s ago)      9m1s
```

Container logs
```
+ kube-green-controller-manager-88d764676-grtp7 › kube-rbac-proxy
kube-green-controller-manager-88d764676-grtp7 kube-rbac-proxy I0324 10:41:05.538150       1 main.go:186] Valid token audiences: 
kube-green-controller-manager-88d764676-grtp7 kube-rbac-proxy I0324 10:41:05.538239       1 main.go:316] Generating self signed cert as no cert is provided
kube-green-controller-manager-88d764676-grtp7 kube-rbac-proxy I0324 10:41:06.173084       1 main.go:366] Starting TCP socket on 0.0.0.0:8443
kube-green-controller-manager-88d764676-grtp7 kube-rbac-proxy I0324 10:41:06.173361       1 main.go:373] Listening securely on 0.0.0.0:8443
+ kube-green-controller-manager-88d764676-grtp7 › manager
kube-green-controller-manager-88d764676-grtp7 manager I0324 10:49:38.172885       1 request.go:690] Waited for 1.038301707s due to client-side throttling, not priority and fairness, request: GET:https://10.201.0.1:443/apis/security.openshift.io/v1?timeout=32s
kube-green-controller-manager-88d764676-grtp7 manager 2023-03-24T10:49:43Z      INFO    controller-runtime.metrics      Metrics server is starting to listen    {"addr": "127.0.0.1:8080"}
kube-green-controller-manager-88d764676-grtp7 manager 2023-03-24T10:49:43Z      INFO    controller-runtime.builder      skip registering a mutating webhook, object does not implement admission.Defaulter or WithDefaulter wasn't called     {"GVK": "kube-green.com/v1alpha1, Kind=SleepInfo"}
kube-green-controller-manager-88d764676-grtp7 manager 2023-03-24T10:49:43Z      INFO    controller-runtime.builder      Registering a validating webhook        {"GVK": "kube-green.com/v1alpha1, Kind=SleepInfo", "path": "/validate-kube-green-com-v1alpha1-sleepinfo"}
kube-green-controller-manager-88d764676-grtp7 manager 2023-03-24T10:49:43Z      INFO    controller-runtime.webhook      Registering webhook     {"path": "/validate-kube-green-com-v1alpha1-sleepinfo"}
kube-green-controller-manager-88d764676-grtp7 manager 2023-03-24T10:49:43Z      INFO    setup   starting manager
kube-green-controller-manager-88d764676-grtp7 manager 2023-03-24T10:49:43Z      INFO    controller-runtime.webhook.webhooks     Starting webhook server
kube-green-controller-manager-88d764676-grtp7 manager 2023-03-24T10:49:43Z      INFO    Starting server {"path": "/metrics", "kind": "metrics", "addr": "127.0.0.1:8080"}
kube-green-controller-manager-88d764676-grtp7 manager 2023-03-24T10:49:43Z      INFO    Starting server {"kind": "health probe", "addr": "[::]:8081"}
kube-green-controller-manager-88d764676-grtp7 manager I0324 10:49:43.430559       1 leaderelection.go:248] attempting to acquire leader lease openshift-operators/2bd226ed.kube-green.com...
kube-green-controller-manager-88d764676-grtp7 manager 2023-03-24T10:49:43Z      INFO    controller-runtime.certwatcher  Updated current TLS certificate
kube-green-controller-manager-88d764676-grtp7 manager 2023-03-24T10:49:43Z      INFO    controller-runtime.webhook      Serving webhook server  {"host": "", "port": 9443}
kube-green-controller-manager-88d764676-grtp7 manager 2023-03-24T10:49:43Z      INFO    controller-runtime.certwatcher  Starting certificate watcher
kube-green-controller-manager-88d764676-grtp7 manager I0324 10:50:00.924221       1 leaderelection.go:258] successfully acquired lease openshift-operators/2bd226ed.kube-green.com
kube-green-controller-manager-88d764676-grtp7 manager 2023-03-24T10:50:00Z      DEBUG   events  kube-green-controller-manager-88d764676-grtp7_e2b1fd43-9356-45ed-a8a7-53881f37c022 became leader      {"type": "Normal", "object": {"kind":"Lease","namespace":"openshift-operators","name":"2bd226ed.kube-green.com","uid":"0e30af23-b9d7-4512-86b4-373c29ac0d0a","apiVersion":"coordination.k8s.io/v1","resourceVersion":"4117336319"}, "reason": "LeaderElection"}
kube-green-controller-manager-88d764676-grtp7 manager 2023-03-24T10:50:00Z      INFO    Starting EventSource    {"controller": "sleepinfo", "controllerGroup": "kube-green.com", "controllerKind": "SleepInfo", "source": "kind source: *v1alpha1.SleepInfo"}
kube-green-controller-manager-88d764676-grtp7 manager 2023-03-24T10:50:00Z      INFO    Starting Controller     {"controller": "sleepinfo", "controllerGroup": "kube-green.com", "controllerKind": "SleepInfo"}
kube-green-controller-manager-88d764676-grtp7 manager 2023-03-24T10:50:01Z      INFO    Starting workers        {"controller": "sleepinfo", "controllerGroup": "kube-green.com", "controllerKind": "SleepInfo", "worker count": 20}
- kube-green-controller-manager-88d764676-grtp7 › manager
```

**Comment by davidebianchi** [comment]
Hi @sastorsl! Have you tried to increase the memory limit?
At the moment, by default it is set to `200Mi` in the community operators. It is possible that with the increase of the number of concurrent reconcile, it is needed more memory.

In the next release, I will increase the default limit to something more, like 300Mi. Does this solve?

**Comment by sastorsl** [comment]
When increasing the limit for the `manager` container to `800ms` it finally started and kept running.
I am, of course, a bit wary of changing the spec of an operator, as it's soon forgotten or overwritten on the next update.

It must be spiking during startup, because when running it sits pretty comfortably on around `218Mi`

```bash
$ k top pods --containers kube-green-controller-manager-8558848b49-7k8np
POD                                              NAME              CPU(cores)   MEMORY(bytes)   
kube-green-controller-manager-8558848b49-7k8np   POD               0m           0Mi             
kube-green-controller-manager-8558848b49-7k8np   kube-rbac-proxy   0m           13Mi            
kube-green-controller-manager-8558848b49-7k8np   manager           0m           218Mi  
```

Was there any major changes in the `0.5` release which might explain why it requires more memory?

**Comment by davidebianchi** [comment]
Yes, I understand. At the next update on operator hub, I will increase the number base resources.

The only change which could explain is the number of concurrent reconciler loop, now set to 20 (instead of 10), but from my tests I hadn't noticed a significant increase in memory. I should check it.

Would you be interested in adding your use case to [adopters](https://kube-green.dev/docs/adopters/)?

**Comment by imdmahajankanika** [comment]
@sastorsl The memory limit has been increased to 400Mi #287 . Could you please verify?

**Comment by sastorsl** [comment]
Thank you @imdmahajankanika

I'm not able to directly verify the change as I'm using this in OpenShift and use the operator.
As I wrote, I've changed the `limit`-setting in the operator config itself, and set it to `800Mi`, so double of your `400Mi`

When restarting the pod (`delete pod`) I see with `top pods` that it levels out at around `518Mi`, before slowly going down to around `240Mi`.

So at least in my case `400Mi` will not be enough.
See above for some numbers regarding namespaces and pods.

```bash
# for i in {1..50}; do echo $(date +%F-%T) $(oc adm top pods -l app=kube-green | grep kube-green) ; sleep 5; done
2023-05-11-19:10:49 kube-green-controller-manager-8558848b49-mr5qm manager 0m 223Mi 
2023-05-11-19:10:55 kube-green-controller-manager-8558848b49-mr5qm manager 0m 223Mi 
2023-05-11-19:11:00 kube-green-controller-manager-8558848b49-mr5qm manager 0m 223Mi 
2023-05-11-19:11:05 kube-green-controller-manager-8558848b49-mr5qm manager 0m 223Mi 
error: metrics not available yet    # At this point I delete the old pod
...
2023-05-11-19:12:18 kube-green-controller-manager-8558848b49-6dvvd 0m 516Mi
2023-05-11-19:12:23 kube-green-controller-manager-8558848b49-6dvvd 0m 516Mi
2023-05-11-19:12:28 kube-green-controller-manager-8558848b49-6dvvd 0m 516Mi
2023-05-11-19:12:34 kube-green-controller-manager-8558848b49-6dvvd 0m 516Mi
2023-05-11-19:12:39 kube-green-controller-manager-8558848b49-6dvvd 0m 516Mi
...
2023-05-11-19:13:25 kube-green-controller-manager-8558848b49-6dvvd 0m 518Mi
2023-05-11-19:13:30 kube-green-controller-manager-8558848b49-6dvvd 0m 518Mi
2023-05-11-19:13:36 kube-green-controller-manager-8558848b49-6dvvd 0m 518Mi
2023-05-11-19:13:41 kube-green-controller-manager-8558848b49-6dvvd 0m 518Mi
2023-05-11-19:13:46 kube-green-controller-manager-8558848b49-6dvvd 1m 518Mi
2023-05-11-19:13:52 kube-green-controller-manager-8558848b49-6dvvd 1m 518Mi
2023-05-11-19:13:57 kube-green-controller-manager-8558848b49-6dvvd 1m 518Mi
2023-05-11-19:14:03 kube-green-controller-manager-8558848b49-6dvvd 1m 518Mi
2023-05-11-19:14:08 kube-green-controller-manager-8558848b49-6dvvd 1m 518Mi
2023-05-11-19:14:13 kube-green-controller-manager-8558848b49-6dvvd 1m 346Mi
2023-05-11-19:14:19 kube-green-controller-manager-8558848b49-6dvvd 1m 346Mi
2023-05-11-19:14:24 kube-green-controller-manager-8558848b49-6dvvd 1m 346Mi
2023-05-11-19:14:29 kube-green-controller-manager-8558848b49-6dvvd 1m 346Mi
2023-05-11-19:14:35 kube-green-controller-manager-8558848b49-6dvvd 1m 346Mi
2023-05-11-19:14:40 kube-green-controller-manager-8558848b49-6dvvd 1m 346Mi
2023-05-11-19:14:45 kube-green-controller-manager-8558848b49-6dvvd 0m 346Mi
2023-05-11-19:14:51 kube-green-controller-manager-8558848b49-6dvvd 0m 346Mi
2023-05-11-19:14:56 kube-green-controller-manager-8558848b49-6dvvd 0m 346Mi
2023-05-11-19:15:01 kube-green-controller-manager-8558848b49-6dvvd 0m 346Mi
2023-05-11-19:15:07 kube-green-controller-manager-8558848b49-6dvvd 0m 346Mi
2023-05-11-19:15:12 kube-green-controller-manager-8558848b49-6dvvd 0m 346Mi
2023-05-11-19:15:17 kube-green-controller-manager-8558848b49-6dvvd 1m 346Mi
2023-05-11-19:15:22 kube-green-controller-manager-8558848b49-6dvvd 1m 346Mi
2023-05-11-19:15:28 kube-green-controller-manager-8558848b49-6dvvd 1m 346Mi
2023-05-11-19:15:33 kube-green-controller-manager-8558848b49-6dvvd 1m 346Mi
2023-05-11-19:15:38 kube-green-controller-manager-8558848b49-6dvvd 1m 346Mi
2023-05-11-19:15:44 kube-green-controller-manager-8558848b49-6dvvd 2m 242Mi
2023-05-11-19:15:49 kube-green-controller-manager-8558848b49-6dvvd 2m 242Mi
2023-05-11-19:15:54 kube-green-controller-manager-8558848b49-6dvvd 2m 242Mi
2023-05-11-19:16:00 kube-green-controller-manager-8558848b49-6dvvd 2m 242Mi
2023-05-11-19:16:05 kube-green-controller-manager-8558848b49-6dvvd 2m 242Mi
2023-05-11-19:16:10 kube-green-controller-manager-8558848b49-6dvvd 2m 242Mi
2023-05-11-19:16:16 kube-green-controller-manager-8558848b49-6dvvd 0m 242Mi
2023-05-11-19:16:21 kube-green-controller-manager-8558848b49-6dvvd 0m 242Mi
2023-05-11-19:16:26 kube-green-controller-manager-8558848b49-6dvvd 0m 242Mi
2023-05-11-19:16:31 kube-green-controller-manager-8558848b49-6dvvd 0m 242Mi
2023-05-11-19:16:37 kube-green-controller-manager-8558848b49-6dvvd 0m 242Mi
2023-05-11-19:16:42 kube-green-controller-manager-8558848b49-6dvvd 0m 242Mi
```

Like you can see, it slows down after the initial setup but peaks well above even 400Mi.

**Comment by imdmahajankanika** [comment]
> Thank you @imdmahajankanika
> 
> I'm not able to directly verify the change as I'm using this in OpenShift and use the operator. As I wrote, I've changed the `limit`-setting in the operator config itself, and set it to `800Mi`, so double of your `400Mi`
> 
> When restarting the pod (`delete pod`) I see with `top pods` that it levels out at around `518Mi`, before slowly going down to around `240Mi`.
> 
> So at least in my case `400Mi` will not be enough. See above for some numbers regarding namespaces and pods.
> 
> ```shell
> # for i in {1..50}; do echo $(date +%F-%T) $(oc adm top pods -l app=kube-green | grep kube-green) ; sleep 5; done
> 2023-05-11-19:10:49 kube-green-controller-manager-8558848b49-mr5qm manager 0m 223Mi 
> 2023-05-11-19:10:55 kube-green-controller-manager-8558848b49-mr5qm manager 0m 223Mi 
> 2023-05-11-19:11:00 kube-green-controller-manager-8558848b49-mr5qm manager 0m 223Mi 
> 2023-05-11-19:11:05 kube-green-controller-manager-8558848b49-mr5qm manager 0m 223Mi 
> error: metrics not available yet    # At this point I delete the old pod
> ...
> 2023-05-11-19:12:18 kube-green-controller-manager-8558848b49-6dvvd 0m 516Mi
> 2023-05-11-19:12:23 kube-green-controller-manager-8558848b49-6dvvd 0m 516Mi
> 2023-05-11-19:12:28 kube-green-controller-manager-8558848b49-6dvvd 0m 516Mi
> 2023-05-11-19:12:34 kube-green-controller-manager-8558848b49-6dvvd 0m 516Mi
> 2023-05-11-19:12:39 kube-green-controller-manager-8558848b49-6dvvd 0m 516Mi
> ...
> 2023-05-11-19:13:25 kube-green-controller-manager-8558848b49-6dvvd 0m 518Mi
> 2023-05-11-19:13:30 kube-green-controller-manager-8558848b49-6dvvd 0m 518Mi
> 2023-05-11-19:13:36 kube-green-controller-manager-8558848b49-6dvvd 0m 518Mi
> 2023-05-11-19:13:41 kube-green-controller-manager-8558848b49-6dvvd 0m 518Mi
> 2023-05-11-19:13:46 kube-green-controller-manager-8558848b49-6dvvd 1m 518Mi
> 2023-05-11-19:13:52 kube-green-controller-manager-8558848b49-6dvvd 1m 518Mi
> 2023-05-11-19:13:57 kube-green-controller-manager-8558848b49-6dvvd 1m 518Mi
> 2023-05-11-19:14:03 kube-green-controller-manager-8558848b49-6dvvd 1m 518Mi
> 2023-05-11-19:14:08 kube-green-controller-manager-8558848b49-6dvvd 1m 518Mi
> 2023-05-11-19:14:13 kube-green-controller-manager-8558848b49-6dvvd 1m 346Mi
> 2023-05-11-19:14:19 kube-green-controller-manager-8558848b49-6dvvd 1m 346Mi
> 2023-05-11-19:14:24 kube-green-controller-manager-8558848b49-6dvvd 1m 346Mi
> 2023-05-11-19:14:29 kube-green-controller-manager-8558848b49-6dvvd 1m 346Mi
> 2023-05-11-19:14:35 kube-green-controller-manager-8558848b49-6dvvd 1m 346Mi
> 2023-05-11-19:14:40 kube-green-controller-manager-8558848b49-6dvvd 1m 346Mi
> 2023-05-11-19:14:45 kube-green-controller-manager-8558848b49-6dvvd 0m 346Mi
> 2023-05-11-19:14:51 kube-green-controller-manager-8558848b49-6dvvd 0m 346Mi
> 2023-05-11-19:14:56 kube-green-controller-manager-8558848b49-6dvvd 0m 346Mi
> 2023-05-11-19:15:01 kube-green-controller-manager-8558848b49-6dvvd 0m 346Mi
> 2023-05-11-19:15:07 kube-green-controller-manager-8558848b49-6dvvd 0m 346Mi
> 2023-05-11-19:15:12 kube-green-controller-manager-8558848b49-6dvvd 0m 346Mi
> 2023-05-11-19:15:17 kube-green-controller-manager-8558848b49-6dvvd 1m 346Mi
> 2023-05-11-19:15:22 kube-green-controller-manager-8558848b49-6dvvd 1m 346Mi
> 2023-05-11-19:15:28 kube-green-controller-manager-8558848b49-6dvvd 1m 346Mi
> 2023-05-11-19:15:33 kube-green-controller-manager-8558848b49-6dvvd 1m 346Mi
> 2023-05-11-19:15:38 kube-green-controller-manager-8558848b49-6dvvd 1m 346Mi
> 2023-05-11-19:15:44 kube-green-controller-manager-8558848b49-6dvvd 2m 242Mi
> 2023-05-11-19:15:49 kube-green-controller-manager-8558848b49-6dvvd 2m 242Mi
> 2023-05-11-19:15:54 kube-green-controller-manager-8558848b49-6dvvd 2m 242Mi
> 2023-05-11-19:16:00 kube-green-controller-manager-8558848b49-6dvvd 2m 242Mi
> 2023-05-11-19:16:05 kube-green-controller-manager-8558848b49-6dvvd 2m 242Mi
> 2023-05-11-19:16:10 kube-green-controller-manager-8558848b49-6dvvd 2m 242Mi
> 2023-05-11-19:16:16 kube-green-controller-manager-8558848b49-6dvvd 0m 242Mi
> 2023-05-11-19:16:21 kube-green-controller-manager-8558848b49-6dvvd 0m 242Mi
> 2023-05-11-19:16:26 kube-green-controller-manager-8558848b49-6dvvd 0m 242Mi
> 2023-05-11-19:16:31 kube-green-controller-manager-8558848b49-6dvvd 0m 242Mi
> 2023-05-11-19:16:37 kube-green-controller-manager-8558848b49-6dvvd 0m 242Mi
> 2023-05-11-19:16:42 kube-green-controller-manager-8558848b49-6dvvd 0m 242Mi
> ```
> 
> Like you can see, it slows down after the initial setup but peaks well above even 400Mi.

That's strange! I am also using kube-green operator on OKD and I manually changed the memory limit to 400Mi and requested 250Mi,  in the the operator config, but the  consumption in my case is between 168Mi and 261Mi ( in the beginning ).

**Comment by davidebianchi** [comment]
What do you think about remove the memory limit from community operators?
The limit depends by the usage (the number of namespaces and pods which the operator handle), and if there is not an effective way to change it, maybe the best solution could be that.
Otherwise, we could set a very high number, but maybe it's better to remove the limit.

**Comment by imdmahajankanika** [comment]
> 

In my opinion, removing the memory limit is not a good idea as removing memory limits could allow community operators to consume more resources than necessary, potentially leading to performance issues, instability, or even crashes.

Instead, we can think of increasing the limit or the other option could be to dynamically adjust the memory limit based on the operator's resource usage, using tools such as Horizontal Pod Autoscaler (HPA).

**Comment by davidebianchi** [comment]
It is not possible to use HPA with this operator at the moment. An operator which adjust itself the resource is not stable, since Kubernetes restart it once the configuration is changed (until k8s 1.27, which should handle the change of resource limits without restart the pod).

I should see if there are some suggestion in the community operators guideline. If not, we should move the memory limit to 1Gib to ensure the use case written above works correctly.

**Comment by davidebianchi** [comment]
I went deeper with the community-operators and the olm (operator lifecycle manager).
I don't know if it's possible from the website, but from the CRD it's possible to change the configuration of the installed operator.
An example of a `Subscription` CRD which changes the resources of the installed operator:

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-kube-green
spec:
  channel: alpha
  name: kube-green
  source: operatorhubio-catalog
  sourceNamespace: olm
  config:
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "1000Mi"
        cpu: "500m"
```

For more details, here the reference of the [Subscription CRD](https://olm.operatorframework.io/docs/concepts/crds/subscription/) and a [openshift docs](https://docs.openshift.com/container-platform/4.12/operators/user/olm-installing-operators-in-namespace.html).

So, it is possible to change the resources configuration directly in olm, without change it from the catalog. So, I would leave the default at 400Mi. 

I close the issue, reopen it if this does not resolve the issue or if you need more support.

**Comment by sastorsl** [comment]
Can confirm and I agree that the issue can be closed.
Thank you for finding the solution here, hidden in plain sight (as always...).

I tested, and changing the Subscriptions `spec` successfully updated the `resources.requests` and `resources.limits` for the running containers in the operator.

One caveat, the settings apply to **all** containers, so for `kube-green` both `manager` and `kube-rbac-proxy` gets updated. This **might** affect you if you are constrained on resources.

**Comment by blezoray** [comment]
Hello, I'm using kube-green 0.5.2 and I have the same issue on my "prod" cluster which is a huge Openshift cluster. Currently, I have only 2 `SleepInfo` CR.

When I starts, the controller consumes about 2 GB memory and then It consumes 1.1GB memory.
![image](https://github.com/kube-green/kube-green/assets/17479277/48224ec9-34e3-41c9-924b-76a37b939418)

I met this experience with several K8S operators developped with OperatorSDK. The generated code watches all the secrets of the cluster (about 20 000 on our prod). So, When the controller starts, it consumes a lot of memory and cpu.

The solution is to set some custom labels on secrets managed by kube-green and watch only these secrets.

Could you investiguate ?

Rgds.

**Comment by davidebianchi** [comment]
Thank you @blezoray for the insight! I create a specific issue on it to investigate on it!
