### ISSUE TITLE
Is there a documentation to upgrade the operator on OKD

### ISSUE THREAD

**Issue by imdmahajankanika** [kube-green/kube-green#304]

**Comment by davidebianchi** [comment]
Hi @imdmahajankanika, not at the moment, but for sure it should be added to the docs.

How do you installed it? At the moment, with kustomize you can deploy the new version with the _make deploy_ command.
Otherwise, you can apply the kube-green.yaml file present in the release.

**Comment by imdmahajankanika** [comment]
> Hi @imdmahajankanika, not at the moment, but for sure it should be added to the docs.
> 
> How do you installed it? At the moment, with kustomize you can deploy the new version with the _make deploy_ command. Otherwise, you can apply the kube-green.yaml file present in the release.

Hello @davidebianchi , I installed it from operator hub on okd

**Comment by imdmahajankanika** [comment]
> With olm, it should be uprgaded automatically. Isn't it?

Yes, you are right! If the update channel is automatic, it's upgraded automatically as per the documentation. But it didn't happen, in our cluster, it is still v0.5.0. So, I was wondering if there is a way to do it manually.

**Comment by davidebianchi** [comment]
Hi @imdmahajankanika, have you solved this? I think it's not related to kube-green configuration.
I close it, reopen if more help needed.
