### ISSUE TITLE
Add keda HPA support

### ISSUE THREAD

**Issue by kernelold** [kube-green/kube-green#344]
To be able to suspend horizontal autoscaling during sleephours.

https://keda.sh/docs/2.8/concepts/scaling-deployments/#pause-autoscaling

**Comment by daoanhminh93** [comment]
So this means we have to manually add the annotation, any ideas on schedule this. I've tried set the minReplicaCount to 0 but it doesn't work.

**Comment by kernelold** [comment]
@daoanhminh93 I think we can just iterate over all the `ScaledObject` resources in the namespace and set this annotation to them:
```
metadata:
  annotations:
    autoscaling.keda.sh/paused-replicas: "0" 
```
when we are going to sleep 
and just remove it on wakeup.
Ideally we should save the condition if this annotation was set before sleep and do not remove on wakeup it if so.

**Comment by davidebianchi** [comment]
I've been working on #363 to support generic resources. I will add a test on this configuration, I think that it should be supported! I've update you on the outcome!
