### ISSUE TITLE
ETA Support k8s version  1.27+

### ISSUE THREAD

**Issue by AmitBaranes** [kube-green/kube-green#356]
We would like to upgrade our cluster to k8s 1.27 and still use kube-green, is there any  ETA to support this version?
Thanks.

**Comment by davidebianchi** [comment]
Hi @AmitBaranes, I'm happy to hear that. 
kube-green already works with Kubernetes 1.27, I create a new PR to add tests with this version and upgrade some dependencies. Once finished the changes in PR, I will also update the docs accordingly.

**Comment by AmitBaranes** [comment]
Thank you for the quick response!

**Comment by davidebianchi** [comment]
The PR which tests the support to K8s version 1.27 and 1.28 is merged into main, and it will be released soon.
As previously said, the current version already support those versions.
