### ISSUE TITLE
Make cert-manager optional on kube-green

### ISSUE THREAD

**Issue by msfidelis** [kube-green/kube-green#433]
I believe the implementation of cert-manager doesn't make much sense for the adoption of kube-green. What are the obstacles to removing it or making it optional in the best-case scenario?

I must confess that, I don't understand how it adds value to the solution. I would be happy to understand more.

**Comment by davidebianchi** [comment]
The cert-manager is needed to expose the validation webhook in kube-green.

I write a documentation on how to manually configure kube-green without the need of the cert-manager, now available on the [kube-green docs](https://kube-green.dev/docs/advanced/webhook-cert-management/).
I also added on the helm chart the possibility to enable an automatic cert configuration without the cert-manager (also documented in the above link).

So, it is now optional to use the cert-manager.
