### ISSUE TITLE
Filter watched secret to only kube-green managed ones

### ISSUE THREAD

**Issue by davidebianchi** [kube-green/kube-green#434]
The code watches all the secrets of the cluster. So, When the controller starts, it consumes a lot of memory and cpu.

The solution is to set some custom labels on secrets managed by kube-green and watch only these secrets.

_Originally posted by @blezoray in https://github.com/kube-green/kube-green/issues/271#issuecomment-2089903991_

**Comment by makinjc** [comment]
We hit this as well, bumped up to memory to 6G for the time being. Out of curiosity, why the design choice is to store previous values are on secrets but not as annotations on the objects itself?

**Comment by davidebianchi** [comment]
Hi @makinjc! The choice was done in order to reduce the amount of changes made to the original manifest. Additionally, other informations are also needed, so there was a need to create a secret to maintain the state anyway.
