### ISSUE TITLE
Release version which supports `patches` from CRD to operatorhub

### ISSUE THREAD

**Issue by davidkarlsen** [kube-green/kube-green#443]
Hi.

I see non-standard k8s-resources are supported via the `patches` property in the crd (from the docs), but this does not seem to be available in operator version v0.5.2 from the operatorhub.

Could you push out latest version that supports this to the operatorhub?

**Comment by davidebianchi** [comment]
Hi! It will be supported in the 0.6.0 tag, which is now in pre release. It is possible to follow the release from this milestone: https://github.com/kube-green/kube-green/milestone/1
Once in GA, it will be released also on operatorhub.

**Comment by davidkarlsen** [comment]
@davidebianchi any closer to GA and operatorhub?

**Comment by davidebianchi** [comment]
Version 0.6.0 was released on OperatorHub on November 11. However, issue #490  remains open, as kube-green cannot be installed in a namespace other than operators. Several approaches have been considered, but no definitive solution has been found yet.

I close this issue, reopen if needed
