### ISSUE TITLE
helm repo not found

### ISSUE THREAD

**Issue by slim-azaiz** [kube-green/kube-green#492]
helm repo add kube-green https://kube-green.github.io/kube-green is not working:

Error: looks like "https://kube-green.github.io/kube-green" is not a valid chart repository or cannot be reached: failed to fetch https://kube-green.github.io/kube-green/index.yaml : 404 Not Found

**Comment by davidebianchi** [comment]
Hi @slim-azaiz! Oh sorry, a typo on the docs. The correct command is:

```sh
helm repo add kube-green  https://kube-green.github.io/helm-charts/
```

I update the documentation!

**Comment by slim-azaiz** [comment]
There is no oci repo ?

**Comment by davidebianchi** [comment]
No, there isn't yet

**Comment by davidebianchi** [comment]
Close this since the original problem is solved. If you need the oci repo, please open another issue!
