### ISSUE TITLE
Typo in Configuration docs

### ISSUE THREAD

**Issue by sergioasantiago** [kube-green/kube-green#499]
While reading the docs [Configuration/#include-with-labels](https://kube-green.dev/docs/configuration/#include-with-labels), I noticed that there is a typo in the SleepInfo definition. It is using the same definition as `exclude-with-labels`, which relies on `excludeRef`. Since we want to include the workloads with specific labels, it should be `includeRef`.

Does it make sense?

**Comment by davidebianchi** [comment]
You're absolutely right, thank you for catching that! The SleepInfo definition should indeed use `includeRef` instead of `excludeRef`.

If you'd like, feel free to open a pull request to correct it! Otherwise, let me know, and I'll be happy to take care of it.

**Comment by sergioasantiago** [comment]
Sure, here we go https://github.com/kube-green/kube-green.github.io/pull/169
